name: Build and deploy Node.js app to Azure Web App - Product-Management

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install backend dependencies
        run: npm install

      - name: Install frontend dependencies and build
        run: |
          npm install --prefix frontend
          npm run build --prefix frontend

      - name: Prepare artifact folder
        run: |
          mkdir publish
          cp -r backend publish/backend
          cp -r frontend/dist publish/frontend/dist
          cp package*.json publish/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_38CE6905197D4AFFB4DFD3837C5FF0DB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_42DB1FB270BA4155B7AE47949400B430 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1AA96B40AF6F415C94DF37E85CFD75BF }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Product-Management'
          slot-name: 'Production'
          package: publish
